name: Build and Deploy Game
on:
  push:
    branches: [ main ] # Робот сработает, когда ты сохранишь изменения в ветке main

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Pygbag
        run: |
          python -m pip install pygbag

      - name: Build Game
        run: |
          # Эта команда соберет твой main.py в папку build/web
          python -m pygbag --build main.py

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # Загружаем только готовую версию сайта
          branch: gh-pages # Отправляем её в специальную ветку для сайтов
